### PR TITLE
Bring back lost customDebugger function

### PR DESCRIPTION
**Pull request by ruslan-bikkinin**
Summary:
---------

PR #52 were supposed to add ESLint to the project but due to [these changes](https://github.com/react-native-community/react-native-cli/pull/52/files#diff-c4b441f65f8822889a54a29511244eef) `customDebugger` function were accidentally (I guess) deleted that led to this issue: https://github.com/Microsoft/vscode-react-native/issues/936 then.

This PR reverts those changes and fixes regression. I renamed `customDebugger` to `startCustomDebugger` to avoid lint problems.

Test Plan:
----------
* `yarn flow`, `yarn lint`, `yarn test` commands show no errors/failed tests;
* I tested this on our [vscode-react-native](https://github.com/Microsoft/vscode-react-native) extension and it fixed our issue.

### CODE REVIEW

**Comment by grabbou** [comment]
I guess we should release it to both branches @thymikee?

**Comment by thymikee** [comment]
@ruslan-bikkinin released 1.4.6 with this fix :)

**Comment by ruslan-bikkinin** [comment]
@thymikee Thanks for taking care of it! Will it be available in the next 0.59.x patch?

**Comment by grabbou** [comment]
@ruslan-bikkinin it's automatically available, just reinstall `node_module`s

**Comment by ruslan-bikkinin** [comment]
Oh, now I see, thanks.

**Pull request merged**
