### PR TITLE
imp: Make package name a required argument in link

### PR DESCRIPTION
**Pull request by Esemesek**
Make `packageName` required in `link` command.
Fixes: #48

### CODE REVIEW

**Comment by thymikee** [comment]
What about linking assets like fonts? Is this still supported somehow?
Here's example of usage: https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e#bcc2
cc @grabbou

**Comment by grabbou** [comment]
Yes, it is still supported. To be honest, I wonder if we should keep it. Linking only a single dependency but, at the same time, linking all the assets, looks to me like a really badly designed behaviour.

I wonder whether we should:
- allow running `link` without a package name that would only link assets from the project itself (like in the document you presented). The downside of this direction is that it's confusing for those who were running `react-native link` without a name before.
- allow running `link` with the project name, e.g `react-native link HelloWorld` where HelloWorld is the `name` inside `package.json` of the project. That would link assets only, since native files are already linked.

**Comment by ferrannp** [comment]
Definitely linked assets is needed. 

> Linking only a single dependency but, at the same time, linking all the assets

That's weird yes, unless the single dependency has assets.

I think something explicit is better, just like:

```sh
react-native link --assets
```

**Comment by thymikee** [comment]
Or linking assets (or whatever there is in the config file) would be performed when no name is passed.

**Comment by grabbou** [comment]
> Or linking assets (or whatever there is in the config file) would be performed when no name is passed.

Problem with this is that it's an implicit breaking change. People running `react-native link` and not being aware of this change, will report problems of native files not being linked.

Since we are forcing the name, I guess the better approach is to require the name of the project itself or... create another command (probably unwanted).

**Pull request merged**
