### PR TITLE
Feature: adds prettier command

### PR DESCRIPTION
**Pull request by sidferreira**
That's a humble suggestion.
As I worked, I missed a lot this command...

### CODE REVIEW

**Comment by thymikee** [comment]
Thanks for the PR.
However that's not necessary, since you can run `yarn lint --fix` to fix all Prettier errors, they're autofixable :)

**Comment by thymikee** [comment]
Feel free to add that to contributing guide, that may be a good idea :)

**Comment by sidferreira** [comment]
@thymikee I really added eslint and prettier to my workflow. But I keep them separated as sometimes I know there are errors and I just want to fix the code :)

**Comment by thymikee** [comment]
In this project prettier and eslint are integrated and they shouldn't collide.

**Pull request closed without merging**
