### PR TITLE
fix: no need from cd - on package.json so we can pass custom arguments

### PR DESCRIPTION
**Pull request by ferrannp**

### CODE REVIEW

**Comment by thymikee** [comment]
This will change your working directory after running tests.
Time to setup Jest `projects` and run tests from the root ;)

**Comment by ferrannp** [comment]
@thymikee it doesn't locally. Isn't that the default behavior of `npm:scripts` ?

**Comment by thymikee** [comment]
If it works, then cool, I'm not aware of such feature :D

**Comment by grabbou** [comment]
@thymikee it depends. Each command on CircleCI runs in its own session, so it always starts from the "workingDirectory". If we have a separate "run" phase for "npm test", it should be good regardless of the "npm scripts" behaviour.

**Comment by grabbou** [comment]
I am going to merge it and we should fix them.

**Pull request merged**
