### PR TITLE
refactor: don't add purge as remote when upgrading

### PR DESCRIPTION
**Pull request by pvinis**
Summary:
---------

I tested without adding any remotes when upgrading, and it seems to be working fine, nothing I saw was affected.

It is based on #242, and it addresses #244.

Test Plan:
----------

Try to upgrade a rn project.

### CODE REVIEW

**Comment by thymikee** [comment]
Just tried this locally and looks like we don't need a remote for 3way merging, yay! (confirmed that it worked without a remote with --3way flag and failed without it to make sure falling back actually does something)

Can you rework this PR to only remove the remote, so without changes from #242?

**Comment by pvinis** [comment]
I can rebase.

**Comment by pvinis** [comment]
👍

**Comment by thymikee** [comment]
Thank you!

**Comment by pvinis** [comment]
I'll go fix the conflicts on the other PR.

**Pull request merged**
